### ISSUE TITLE
Autocorrect with rubocop

### ISSUE THREAD

**Issue by jcoyne** [Shopify/erb_lint#383]
When my config is:
```yml
---
EnableDefaultLinters: true
linters:
  ErbSafety:
    enabled: true
  Rubocop:
    enabled: true
```
and I run `erb_lint -a` it does this correction.

```
+++ b/app/views/blacklight/nav/_search_history.html.erb
@@ -1 +1,3 @@
-<%= link_to t('blacklight.header_links.search_history'), blacklight.search_history_path, class: 'nav-link' %>
+# frozen_string_literal: true
+link_to t('blacklight.header_links.search_history'), blacklight.search_history_path, class: 'nav-link'
+ %>
```

This drops the opening `<%= ` tag.
