### ISSUE TITLE
Rubocop plugins support

### ISSUE THREAD

**Issue by jbigler** [Shopify/erb_lint#402]
We recently upgraded `rubocop` and `rubocop-rails`. When running rubocop, we receive the following error.
```
rubocop-rails extension supports plugin, specify `plugins: rubocop-rails` instead of `require: rubocop-rails` in /Users/minktom/Dev/rails-core/.rubocop.yml.
For more information, see https://docs.rubocop.org/rubocop/plugin_migration_guide.html.
```
However, if we switch from `require` to `plugins` for `rubocop-rails`, `erb_lint` no longer detects errors from the Rails Cops. But if we go back to `require` to get `erb_lint` working again, we have issues with rubocop sometimes throwing thousands of errors. There may be a few different issues interacting with one another (bundler interacting with rubocop plugins/require), but either way it seems that `erb_lint` should be able to support rubocop plugin extensions as well as those that are required.

```yml
...
linters:
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
        - .erb_lint_rubocop.yml
```

`require: rubocop-rails`

![Image](https://github.com/user-attachments/assets/f4f45b11-82cb-4548-bcca-5cdd0d623912)

`plugins: rubocop-rails`

![Image](https://github.com/user-attachments/assets/c2a05e78-6a32-4ba2-9eee-4dd006f9c860)
